### ISSUE TITLE
Read from stdin and write to stdout

### ISSUE THREAD

**Issue by cfuehrmann** [hougesen/kdlfmt#23]
To use this as a formatter e.g. in the Helix editor, it would be great to have a variant of this command that reads the kdl from stdin and writes it to stdout. Have you considered that?

**Comment by hougesen** [comment]
Makes sense. I'll add that 😄

**Comment by cfuehrmann** [comment]
Thanks, your change works for me! (Now all I have left to do is head over to kdl-rs and create an issue about a gargantuan formatting error...)
