### ISSUE TITLE
Support EditorConfig as inputs

### ISSUE THREAD

**Issue by toastal** [hougesen/kdlfmt#54]
I would like to see EditorConfig be used as a fallback for the default spacing when no format values are specified.

Advantages: keep indentation config in one place; no desync in config/execution; no need to pass arguments or override; ability to specify different values for different files/directories if needed for vendored third-party files

Disadvantages: requires parsing `.editorconfig`, a third-party format & would incur additional dependencies; minor endorsement of EditorConfig as a project since it would get special support

See response: https://github.com/kdl-org/kdl-rs/issues/96#issuecomment-2525061644

**Comment by hougesen** [comment]
Good idea! 

#55 added support for specifying indentation level using a custom `kdlfmt` config file. Adding fallback support for editorconfig should be pretty straightforward 😄
