### ISSUE TITLE
KDL 2.0.0 support

### ISSUE THREAD

**Issue by zkat** [hougesen/kdlfmt#56]
Heya!

kdl-rs has released [version 6.0.0](https://github.com/kdl-org/kdl-rs/releases/tag/v6.0.0), which supports [KDL 2.0.0](https://github.com/kdl-org/kdl/releases/tag/2.0.0)!

The library now also supports autoconversion between v1 and v2 documents (and vice versa), including doing so with minimal changes (that is, without autoformatting as well)

**Comment by hougesen** [comment]
Awesome! 

Should be pretty quick to implement 😄
